on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Check Commit

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1
      with:
        version: v1.56.2
        only-new-issues: true

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
    - name: test
      run: go test
